insert into tour_operator values("MYT2312","Mythos Tours","Qal eh-ye1131",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Mariehamn1137",2,"Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Kruje1143",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Jijel1149",6,"Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Pago Pago1155",1,"Very Poor");
insert into tour_operator values("PAN4738","Pan Tours","Andorra1161",7,"Very Good");
insert into tour_operator values("PAN4738","Pan Tours","Mucusso1167",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","de Noviembre1173",4,"Average");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Ashtarak1179",10,"The best tour operator");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Oranjestad1185",0,"Not Rated");
insert into tour_operator values("TAN7563","Tandas Tours","Central Coast1191",8,"Awesome");
insert into tour_operator values("MYT2312","Mythos Tours","Bregenz1197",0,"Not Rated");
insert into tour_operator values("BAM7523","Bambooo Tours","Gadabay1203",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Manama1209",10,"The best tour operator");
insert into tour_operator values("TAN7563","Tandas Tours","Tangail1215",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Bridgetown1221",7,"Very Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Baranavichy1227",3,"Mediocre");
insert into tour_operator values("PUB7458","PUBG Tours","Mons1233",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","El Cayo1239",8,"Awesome");
insert into tour_operator values("TAN7563","Tandas Tours","Lokossa1245",10,"The best tour operator");
insert into tour_operator values("PUB7458","PUBG Tours","Hamilton1251",10,"The best tour operator");
insert into tour_operator values("PUB7458","PUBG Tours","Paro1257",1,"Very Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Punata1263",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Zenica1269",9,"Outstanding");
insert into tour_operator values("TAN7563","Tandas Tours","Mochudi1275",6,"Good");
insert into tour_operator values("PUB7458","PUBG Tours","Grajau1281",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Bandar Seri Begawan1287",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Lovec1293",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Fada Ngourma1299",5,"Better than many other operators");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Cankuzo1305",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Kampong Spoe1311",4,"Average");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Buea1317",3,"Mediocre");
insert into tour_operator values("KRI8347","Krishna Tours","Selkirk1323",9,"Outstanding");
insert into tour_operator values("BAM7523","Bambooo Tours","Mindelo1329",2,"Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","George Town1335",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Mobaye1341",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Lai1347",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Rio Verde1353",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Yumen1359",2,"Poor");
insert into tour_operator values("TAN7563","Tandas Tours","Yopal1365",9,"Outstanding");
insert into tour_operator values("MYT2312","Mythos Tours","Moroni1371",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Madingou1377",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Buluko1383",9,"Outstanding");
insert into tour_operator values("TAN7563","Tandas Tours","Rarotonga1389",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Heredia1395",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Sibenik1401",8,"Awesome");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Ciego de Avila1407",8,"Awesome");
insert into tour_operator values("TAN7563","Tandas Tours","Willemstad1413",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Larnaka1419",9,"Outstanding");
insert into tour_operator values("BAM7523","Bambooo Tours","Usti Nad Labem1425",9,"Outstanding");
insert into tour_operator values("TAN7563","Tandas Tours","Vejle1431",3,"Mediocre");
insert into tour_operator values("PAN4738","Pan Tours","Dikhil1437",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Roseau1443",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Sabaneta1449",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Dili1455",8,"Awesome");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Puyo1461",1,"Very Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Shibin el Kom1467",7,"Very Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Ahuachapan1473",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Evinayong1479",10,"The best tour operator");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Tessenei1485",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Haapsalu1491",2,"Poor");
insert into tour_operator values("MYT2312","Mythos Tours","Awasa1497",3,"Mediocre");
insert into tour_operator values("APH9348","Aphrodite Tours","Fox Bay1503",3,"Mediocre");
insert into tour_operator values("APH9348","Aphrodite Tours","Klaksvik1509",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Palikir1515",8,"Awesome");
insert into tour_operator values("MYT2312","Mythos Tours","Nandi1521",5,"Better than many other operators");
insert into tour_operator values("APH9348","Aphrodite Tours","Hameenlinna1527",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Annecy1533",6,"Good");
insert into tour_operator values("PAN4738","Pan Tours","Papeete1539",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Ebebiyin1545",7,"Very Good");
insert into tour_operator values("KRI8347","Krishna Tours","Kutaisi1551",5,"Better than many other operators");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Mainz1557",9,"Outstanding");
insert into tour_operator values("MYT2312","Mythos Tours","Sunyani1563",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Gibraltar1569",5,"Better than many other operators");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Lamia1575",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Qasigiannguit1581",8,"Awesome");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Saint George's1587",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Agana1593",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Salama1599",1,"Very Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Mali1605",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Cacheu1611",6,"Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Corriverton1617",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Jeremie1623",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Yoro1629",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Hong Kong1635",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Veszprem1641",8,"Awesome");
insert into tour_operator values("TAN7563","Tandas Tours","Borgarnes1647",0,"Not Rated");
insert into tour_operator values("MYT2312","Mythos Tours","Panaji1653",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Binjai1659",2,"Poor");
insert into tour_operator values("TAN7563","Tandas Tours","Yasuj1665",6,"Good");
insert into tour_operator values("KRI8347","Krishna Tours","Dahuk1671",9,"Outstanding");
insert into tour_operator values("PUB7458","PUBG Tours","Ros Comain1677",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Douglas1683",8,"Awesome");
insert into tour_operator values("PAN4738","Pan Tours","Ramla1689",8,"Awesome");
insert into tour_operator values("PAN4738","Pan Tours","Potenza1695",4,"Average");
insert into tour_operator values("PUB7458","PUBG Tours","Touba1701",8,"Awesome");
insert into tour_operator values("TAN7563","Tandas Tours","Lucea1707",8,"Awesome");
insert into tour_operator values("PAN4738","Pan Tours","Okayama1713",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Al Mafraq1719",7,"Very Good");
insert into tour_operator values("KRI8347","Krishna Tours","Turgay1725",2,"Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Nyeri1731",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Tarawa1737",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Prizren1743",3,"Mediocre");
insert into tour_operator values("BAM7523","Bambooo Tours","Hawalli1749",8,"Awesome");
insert into tour_operator values("KRI8347","Krishna Tours","Tokmak1755",1,"Very Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Ban Houayxay1761",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Rezekne1767",0,"Not Rated");
insert into tour_operator values("PUB7458","PUBG Tours","B'abda1773",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Teyateyaneng1779",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Barclayville1785",7,"Very Good");
insert into tour_operator values("PAN4738","Pan Tours","Dirj1791",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Vaduz1797",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Panevezys1803",6,"Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Diekirch1809",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Macau1815",5,"Better than many other operators");
insert into tour_operator values("PUB7458","PUBG Tours","Tetovo1821",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Sambava1827",4,"Average");
insert into tour_operator values("PUB7458","PUBG Tours","Mzimba1833",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Kangar1839",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Male1845",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Goundam1851",0,"Not Rated");
insert into tour_operator values("TAN7563","Tandas Tours","Valletta1857",0,"Not Rated");
insert into tour_operator values("PAN4738","Pan Tours","Majuro1863",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Fderik1869",7,"Very Good");
insert into tour_operator values("MYT2312","Mythos Tours","Curepipe1875",8,"Awesome");
insert into tour_operator values("PUB7458","PUBG Tours","Vicente Guerrero1881",1,"Very Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Dubasari1887",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Monaco1893",4,"Average");
insert into tour_operator values("KRI8347","Krishna Tours","Suchboatar1899",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Podgorica1905",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Ksar El Kebir1911",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Moatize1917",0,"Not Rated");
insert into tour_operator values("PAN4738","Pan Tours","Loikaw1923",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Omaruru1929",0,"Not Rated");
insert into tour_operator values("BAM7523","Bambooo Tours","Sallyan1935",3,"Mediocre");
insert into tour_operator values("KRI8347","Krishna Tours","Assen1941",5,"Better than many other operators");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Noumea1947",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Greymouth1953",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Somoto1959",4,"Average");
insert into tour_operator values("PUB7458","PUBG Tours","Goure1965",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Umuahia1971",0,"Not Rated");
insert into tour_operator values("PUB7458","PUBG Tours","Sariwon1977",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kyrenia1983",4,"Average");
insert into tour_operator values("MYT2312","Mythos Tours","Capitol Hill1989",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Arendal1995",1,"Very Poor");
insert into tour_operator values("MYT2312","Mythos Tours","Alayat Samail2001",3,"Mediocre");
insert into tour_operator values("PUB7458","PUBG Tours","Parachinar2007",7,"Very Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Koror2013",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Ramallah2019",6,"Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","El Porvenir2025",0,"Not Rated");
insert into tour_operator values("PAN4738","Pan Tours","Wabag2031",1,"Very Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Mariscal Jose F. Estigarribia2037",1,"Very Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Ferrenafe2043",8,"Awesome");
insert into tour_operator values("PUB7458","PUBG Tours","San Carlos2049",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Olsztyn2055",1,"Very Poor");
insert into tour_operator values("MYT2312","Mythos Tours","Aveiro2061",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Ponce2067",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Doha2073",6,"Good");
insert into tour_operator values("KRI8347","Krishna Tours","Targu Jiu2079",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Nazran2085",0,"Not Rated");
insert into tour_operator values("BAM7523","Bambooo Tours","Gikongoro2091",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Basseterre2097",5,"Better than many other operators");
insert into tour_operator values("APH9348","Aphrodite Tours","Castries2103",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Apia2109",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","San Marino2115",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Santo Antonio2121",8,"Awesome");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","An Nabk2127",1,"Very Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Fatick2133",7,"Very Good");
insert into tour_operator values("MYT2312","Mythos Tours","Subotica2139",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Victoria2145",8,"Awesome");
insert into tour_operator values("KRI8347","Krishna Tours","Makeni2151",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Singapore2157",10,"The best tour operator");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Banska Bystrica2163",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Maribor2169",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Gizo2175",0,"Not Rated");
insert into tour_operator values("KRI8347","Krishna Tours","Xuddur2181",5,"Better than many other operators");
insert into tour_operator values("APH9348","Aphrodite Tours","Laascaanood2187",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Qacha's Nek2193",7,"Very Good");
insert into tour_operator values("KRI8347","Krishna Tours","Grytviken2199",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Eumseong2205",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Bentiu2211",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Merida2217",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Trincomalee2223",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Ed Damazin2229",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Onverwacht2235",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Piggs Peak2241",1,"Very Poor");
insert into tour_operator values("TAN7563","Tandas Tours","Falun2247",1,"Very Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Delemont2253",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Dar'a2259",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Bade2265",0,"Not Rated");
insert into tour_operator values("TAN7563","Tandas Tours","Leninobod2271",6,"Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Wete2277",6,"Good");
insert into tour_operator values("PUB7458","PUBG Tours","Mae Hong Son2283",3,"Mediocre");
insert into tour_operator values("KRI8347","Krishna Tours","Freeport2289",3,"Mediocre");
insert into tour_operator values("APH9348","Aphrodite Tours","Georgetown2295",5,"Better than many other operators");
insert into tour_operator values("BAM7523","Bambooo Tours","Bassar2301",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Neiafu2307",8,"Awesome");
insert into tour_operator values("PAN4738","Pan Tours","San Fernando2313",7,"Very Good");
insert into tour_operator values("KRI8347","Krishna Tours","Medemine2319",3,"Mediocre");
insert into tour_operator values("PAN4738","Pan Tours","Kirklareli2325",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Gyzlarbat2331",10,"The best tour operator");
insert into tour_operator values("KRI8347","Krishna Tours","Grand Turk2337",7,"Very Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Funafuti2343",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kalangala2349",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","Mykolayiv2355",3,"Mediocre");
insert into tour_operator values("MYT2312","Mythos Tours","Umm al Qaywayn2361",10,"The best tour operator");
insert into tour_operator values("PUB7458","PUBG Tours","Greenock2367",1,"Very Poor");
insert into tour_operator values("PAN4738","Pan Tours","Christiansted2373",7,"Very Good");
insert into tour_operator values("MYT2312","Mythos Tours","Colonia del Sacramento2379",3,"Mediocre");
insert into tour_operator values("KRI8347","Krishna Tours","Khujayli2385",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Luganville2391",6,"Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Vatican City2397",3,"Mediocre");
insert into tour_operator values("APH9348","Aphrodite Tours","San Carlos2403",7,"Very Good");
insert into tour_operator values("MYT2312","Mythos Tours","Tay Ninh2409",9,"Outstanding");
insert into tour_operator values("TAN7563","Tandas Tours","Bir Lehlou2415",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Al Bayda2421",3,"Mediocre");
insert into tour_operator values("BAM7523","Bambooo Tours","Kawambwa2427",4,"Average");
insert into tour_operator values("KRI8347","Krishna Tours","Mazowe2433",10,"The best tour operator");
insert into tour_operator values("MYT2312","Mythos Tours","Beyla2439",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Gueckedou2445",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Dinguiraye2451",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Dabola2457",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kerouane2463",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Siguiri2469",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Mamou2475",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kamsar2481",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Fria2487",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Macenta2493",10,"The best tour operator");
insert into tour_operator values("MYT2312","Mythos Tours","Yomou2499",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Faranah2505",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kissidougou2511",0,"Not Rated");
insert into tour_operator values("MYT2312","Mythos Tours","Labe2517",2,"Poor");
insert into tour_operator values("MYT2312","Mythos Tours","Boke2523",5,"Better than many other operators");
insert into tour_operator values("MYT2312","Mythos Tours","Kindia2529",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Kankan2535",9,"Outstanding");
insert into tour_operator values("MYT2312","Mythos Tours","Nzerekore2541",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Conakry2547",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","Cacheu2553",3,"Mediocre");
insert into tour_operator values("PUB7458","PUBG Tours","Farim2559",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Fulacunda2565",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Gabu2571",3,"Mediocre");
insert into tour_operator values("BAM7523","Bambooo Tours","Catio2577",1,"Very Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Bolama2583",8,"Awesome");
insert into tour_operator values("MYT2312","Mythos Tours","Bafata2589",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Bissau2595",5,"Better than many other operators");
insert into tour_operator values("MYT2312","Mythos Tours","Corriverton2601",10,"The best tour operator");
insert into tour_operator values("PUB7458","PUBG Tours","Ituni2607",2,"Poor");
insert into tour_operator values("PAN4738","Pan Tours","Lethem2613",5,"Better than many other operators");
insert into tour_operator values("PUB7458","PUBG Tours","Kumaka2619",1,"Very Poor");
insert into tour_operator values("PAN4738","Pan Tours","Bartica2625",6,"Good");
insert into tour_operator values("PUB7458","PUBG Tours","Anna Regina2631",8,"Awesome");
insert into tour_operator values("KRI8347","Krishna Tours","Linden2637",8,"Awesome");
insert into tour_operator values("MYT2312","Mythos Tours","Mabaruma2643",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","New Amsterdam2649",1,"Very Poor");
insert into tour_operator values("BAM7523","Bambooo Tours","Georgetown2655",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Jeremie2661",10,"The best tour operator");
insert into tour_operator values("PUB7458","PUBG Tours","Port-De-Paix2667",7,"Very Good");
insert into tour_operator values("PAN4738","Pan Tours","Hinche2673",4,"Average");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Fort-Liberte2679",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Jacmel2685",1,"Very Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Les Cayes2691",4,"Average");
insert into tour_operator values("KRI8347","Krishna Tours","Gonaives2697",3,"Mediocre");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Cap-Haitien2703",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Port-au-Prince2709",10,"The best tour operator");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Yoro2715",3,"Mediocre");
insert into tour_operator values("PAN4738","Pan Tours","La Esperanza2721",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","La Paz2727",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Santa Barbara2733",3,"Mediocre");
insert into tour_operator values("TAN7563","Tandas Tours","Gracias2739",5,"Better than many other operators");
insert into tour_operator values("MYT2312","Mythos Tours","Nueva Ocotepeque2745",6,"Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Yuscaran2751",0,"Not Rated");
insert into tour_operator values("KRI8347","Krishna Tours","Roatan2757",5,"Better than many other operators");
insert into tour_operator values("BAM7523","Bambooo Tours","Nacaome2763",0,"Not Rated");
insert into tour_operator values("KRI8347","Krishna Tours","Santa Rosa de Copan2769",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Trujillo2775",8,"Awesome");
insert into tour_operator values("PAN4738","Pan Tours","Brus Laguna2781",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Puerto Lempira2787",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Juticalpa2793",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Comayagua2799",5,"Better than many other operators");
insert into tour_operator values("TAN7563","Tandas Tours","Choluteca2805",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","La Ceiba2811",2,"Poor");
insert into tour_operator values("PAN4738","Pan Tours","San Pedro Sula2817",5,"Better than many other operators");
insert into tour_operator values("KRI8347","Krishna Tours","Tegucigalpa2823",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Hong Kong2829",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Veszprem2835",8,"Awesome");
insert into tour_operator values("PUB7458","PUBG Tours","Zalaegerszeg2841",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","Tatabanya2847",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Szekszard2853",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Salgotarjan2859",2,"Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Bekescsaba2865",3,"Mediocre");
insert into tour_operator values("APH9348","Aphrodite Tours","Eger2871",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Szombathely2877",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Kecskemet2883",8,"Awesome");
insert into tour_operator values("MYT2312","Mythos Tours","Szekesfehervar2889",4,"Average");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Nyiregyhaza2895",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Pecs2901",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Gyor2907",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Kaposvar2913",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Vac2919",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Miskolc2925",3,"Mediocre");
insert into tour_operator values("BAM7523","Bambooo Tours","Szeged2931",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Debrecen2937",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Szolnok2943",5,"Better than many other operators");
insert into tour_operator values("BAM7523","Bambooo Tours","Budapest2949",8,"Awesome");
insert into tour_operator values("PUB7458","PUBG Tours","Borgarnes2955",3,"Mediocre");
insert into tour_operator values("MYT2312","Mythos Tours","Egilsstadir2961",2,"Poor");
insert into tour_operator values("PAN4738","Pan Tours","Saudarkrokur2967",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Selfoss2973",6,"Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Hofn2979",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Isafjordur2985",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Akureyi2991",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Keflavik2997",10,"The best tour operator");
insert into tour_operator values("MYT2312","Mythos Tours","Reykjavik3003",1,"Very Poor");
insert into tour_operator values("APH9348","Aphrodite Tours","Panaji3009",7,"Very Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Simla3015",2,"Poor");
insert into tour_operator values("PAN4738","Pan Tours","Gurgaon3021",9,"Outstanding");
insert into tour_operator values("APH9348","Aphrodite Tours","Sonipat3027",1,"Very Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Rohtak3033",7,"Very Good");
insert into tour_operator values("MYT2312","Mythos Tours","Hisar3039",0,"Not Rated");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Bhiwani3045",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Ambala3051",3,"Mediocre");
insert into tour_operator values("PAN4738","Pan Tours","Sopur3057",9,"Outstanding");
insert into tour_operator values("PAN4738","Pan Tours","Silvassa3063",3,"Mediocre");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kalyan3069",4,"Average");
insert into tour_operator values("APH9348","Aphrodite Tours","Bhusawal3075",2,"Poor");
insert into tour_operator values("KRI8347","Krishna Tours","Jorhat3081",7,"Very Good");
insert into tour_operator values("KRI8347","Krishna Tours","Hoshiarpur3087",0,"Not Rated");
insert into tour_operator values("MYT2312","Mythos Tours","Ajmer3093",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Hathras3099",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Sitapur3105",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Pilibhit3111",5,"Better than many other operators");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Budaun3117",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Firozabad3123",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Mathura3129",8,"Awesome");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Bulandshahr3135",9,"Outstanding");
insert into tour_operator values("PUB7458","PUBG Tours","Hapur3141",5,"Better than many other operators");
insert into tour_operator values("TAN7563","Tandas Tours","Muzaffarnagar3147",0,"Not Rated");
insert into tour_operator values("TAN7563","Tandas Tours","Gangtok3153",1,"Very Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Diu3159",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Pathankot3165",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Sirsa3171",3,"Mediocre");
insert into tour_operator values("BAM7523","Bambooo Tours","Panipat3177",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Karnal3183",3,"Mediocre");
insert into tour_operator values("PUB7458","PUBG Tours","Baramula3189",1,"Very Poor");
insert into tour_operator values("BAM7523","Bambooo Tours","Proddatur3195",2,"Poor");
insert into tour_operator values("BAM7523","Bambooo Tours","Nandyal3201",10,"The best tour operator");
insert into tour_operator values("MYT2312","Mythos Tours","Hindupur3207",10,"The best tour operator");
insert into tour_operator values("BAM7523","Bambooo Tours","Tirupati3213",9,"Outstanding");
insert into tour_operator values("TAN7563","Tandas Tours","Ongole3219",6,"Good");
insert into tour_operator values("PAN4738","Pan Tours","Vizianagaram3225",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Rajahmundry3231",8,"Awesome");
insert into tour_operator values("BAM7523","Bambooo Tours","Machilipatnam3237",4,"Average");
insert into tour_operator values("BAM7523","Bambooo Tours","Khammam3243",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Chirala3249",7,"Very Good");
insert into tour_operator values("APH9348","Aphrodite Tours","Karimnagar3255",8,"Awesome");
insert into tour_operator values("APH9348","Aphrodite Tours","Nizamabad3261",9,"Outstanding");
insert into tour_operator values("PUB7458","PUBG Tours","Kollam3267",6,"Good");
insert into tour_operator values("PUB7458","PUBG Tours","Alappuzha3273",2,"Poor");
insert into tour_operator values("BAM7523","Bambooo Tours","Puri3279",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Sambalpur3285",1,"Very Poor");
insert into tour_operator values("TAN7563","Tandas Tours","Raurkela3291",7,"Very Good");
insert into tour_operator values("PAN4738","Pan Tours","Kavaratti3297",4,"Average");
insert into tour_operator values("PAN4738","Pan Tours","Mandya3303",0,"Not Rated");
insert into tour_operator values("TAN7563","Tandas Tours","Kolar3309",10,"The best tour operator");
insert into tour_operator values("APH9348","Aphrodite Tours","Shimoga3315",6,"Good");
insert into tour_operator values("PUB7458","PUBG Tours","Raichur3321",6,"Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Hospet3327",9,"Outstanding");
insert into tour_operator values("PUB7458","PUBG Tours","Bidar3333",9,"Outstanding");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Sangli3339",2,"Poor");
insert into tour_operator values("PUB7458","PUBG Tours","Parbhani3345",4,"Average");
insert into tour_operator values("TAN7563","Tandas Tours","Malegaon3351",4,"Average");
insert into tour_operator values("PUB7458","PUBG Tours","Port Blair3357",9,"Outstanding");
insert into tour_operator values("MYT2312","Mythos Tours","Tezpur3363",5,"Better than many other operators");
insert into tour_operator values("TAN7563","Tandas Tours","Silchar3369",6,"Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Kohima3375",0,"Not Rated");
insert into tour_operator values("APH9348","Aphrodite Tours","Shillong3381",2,"Poor");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Abohar3387",6,"Good");
insert into tour_operator values("PAN4738","Pan Tours","Patiala3393",1,"Very Poor");
insert into tour_operator values("TAN7563","Tandas Tours","Bhilwara3399",7,"Very Good");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Pali3405",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Tonk3411",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Sikar3417",4,"Average");
insert into tour_operator values("BOO8423","Boozey Woozey Tours","Bikaner3423",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Bharatpur3429",7,"Very Good");
insert into tour_operator values("TAN7563","Tandas Tours","Alwar3435",6,"Good");
insert into tour_operator values("BAM7523","Bambooo Tours","Fatehpur3441",9,"Outstanding");
insert into tour_operator values("MYT2312","Mythos Tours","Faizabad3447",0,"Not Rated");
insert into tour_operator values("BAM7523","Bambooo Tours","Bahraich3453",7,"Very Good");
insert into tour_operator values("PUB7458","PUBG Tours","Mirzapur3459",6,"Good");
insert into tour_operator values("TAN7563","Tandas Tours","Jhansi3465",6,"Good");
insert into tour_operator values("MYT2312","Mythos Tours","Shahjahanpur3471",5,"Better than many other operators");
insert into tour_operator values("PAN4738","Pan Tours","Rampur3477",9,"Outstanding");
insert into tour_operator values("KRI8347","Krishna Tours","Bareilly3483",10,"The best tour operator");
insert into tour_operator values("PAN4738","Pan Tours","Etawah3489",3,"Mediocre");
insert into tour_operator values("PAN4738","Pan Tours","Dehra Dun3495",10,"The best tour operator");
insert into tour_operator values("KRI8347","Krishna Tours","Haora3501",5,"Better than many other operators");
insert into tour_operator values("MYT2312","Mythos Tours","Alipur Duar3507",10,"The best tour operator");
