insert into tourist_destination values("Qal eh-ye","Afghanistan","September",6,"AFG7770");
insert into tourist_destination values("Chaghcharan","Afghanistan","September",3,"AFG3350");
insert into tourist_destination values("Lashkar Gah","Afghanistan","December",2,"AFG6490");
insert into tourist_destination values("Zaranj","Afghanistan","February",2,"AFG270");
insert into tourist_destination values("Tarin Kowt","Afghanistan","March",9,"AFG7630");
insert into tourist_destination values("Zareh Sharan","Afghanistan","December",0,"AFG4260");
insert into tourist_destination values("Asadabad","Afghanistan","June",6,"AFG2110");
insert into tourist_destination values("Taloqan","Afghanistan","October",7,"AFG4290");
insert into tourist_destination values("Mahmud-E Eraqi","Afghanistan","March",0,"AFG8620");
insert into tourist_destination values("Mehtar Lam","Afghanistan","September",7,"AFG1350");
insert into tourist_destination values("Baraki Barak","Afghanistan","July",2,"AFG220");
insert into tourist_destination values("Aybak","Afghanistan","August",9,"AFG1670");
insert into tourist_destination values("Mayda Shahr","Afghanistan","February",6,"AFG110");
insert into tourist_destination values("Karokh","Afghanistan","December",9,"AFG3730");
insert into tourist_destination values("Sheberghan","Afghanistan","November",9,"AFG7840");
insert into tourist_destination values("Pol-e Khomri","Afghanistan","February",8,"AFG3240");
insert into tourist_destination values("Balkh","Afghanistan","0",0,"(null)0");
insert into tourist_destination values("Meymaneh","Afghanistan","December",1,"AFG9800");
insert into tourist_destination values("Andkhvoy","Afghanistan","October",3,"AFG8620");
insert into tourist_destination values("Qalat","Afghanistan","March",6,"AFG2810");
insert into tourist_destination values("Ghazni","Afghanistan","November",5,"AFG840");
insert into tourist_destination values("Feyzabad","Afghanistan","April",6,"AFG5050");
insert into tourist_destination values("Kondoz","Afghanistan","December",9,"AFG3130");
insert into tourist_destination values("Jalalabad","Afghanistan","July",4,"AFG8950");
insert into tourist_destination values("Charikar","Afghanistan","August",5,"AFG8140");
insert into tourist_destination values("Gardiz","Afghanistan","April",4,"AFG3640");
insert into tourist_destination values("Bamian","Afghanistan","April",0,"AFG870");
insert into tourist_destination values("Baghlan","Afghanistan","January",6,"AFG1780");
insert into tourist_destination values("Farah","Afghanistan","October",4,"AFG4030");
insert into tourist_destination values("Herat","Afghanistan","4",0,"(null)0");
insert into tourist_destination values("Mazar-e Sharif","Afghanistan","January",0,"AFG6760");
insert into tourist_destination values("Kandahar","Afghanistan","January",9,"AFG120");
insert into tourist_destination values("Kabul","Afghanistan","December",6,"AFG940");
insert into tourist_destination values("Mariehamn","Aland","5",0,"(null)0");
insert into tourist_destination values("Kruje","Albania","March",8,"ALB4670");
insert into tourist_destination values("Fier","Albania","November",7,"ALB9020");
insert into tourist_destination values("Lushnje","Albania","November",2,"ALB6520");
insert into tourist_destination values("Puke","Albania","October",1,"ALB2800");
insert into tourist_destination values("Bajram Curri","Albania","March",1,"ALB8650");
insert into tourist_destination values("Kukes","Albania","July",4,"ALB6190");
insert into tourist_destination values("Sarande","Albania","June",9,"ALB310");
insert into tourist_destination values("Erseke","Albania","February",7,"ALB7710");
insert into tourist_destination values("Pogradec","Albania","November",5,"ALB7090");
insert into tourist_destination values("Korce","Albania","September",7,"ALB8560");
insert into tourist_destination values("Berat","Albania","July",3,"ALB5860");
insert into tourist_destination values("Corovode","Albania","July",6,"ALB6830");
insert into tourist_destination values("Gramsh","Albania","4",0,"(null)0");
insert into tourist_destination values("Librazhd","Albania","April",2,"ALB8290");
insert into tourist_destination values("Tepelene","Albania","April",9,"ALB2700");
insert into tourist_destination values("Permet","Albania","January",8,"ALB7150");
insert into tourist_destination values("Gjirokaster","Albania","June",9,"ALB7960");
insert into tourist_destination values("Peshkopi","Albania","8",0,"(null)0");
insert into tourist_destination values("Burrel","Albania","March",1,"ALB9210");
insert into tourist_destination values("Lezhe","Albania","9",0,"(null)0");
insert into tourist_destination values("Rreshen","Albania","October",8,"ALB8410");
insert into tourist_destination values("Vlore","Albania","March",3,"ALB5000");
insert into tourist_destination values("Elbasan","Albania","March",4,"ALB1240");
insert into tourist_destination values("Durres","Albania","December",7,"ALB8560");
insert into tourist_destination values("Shkoder","Albania","April",1,"ALB2270");
insert into tourist_destination values("Tirana","Albania","February",9,"ALB9360");
insert into tourist_destination values("Jijel","Algeria","June",1,"DZA4370");
insert into tourist_destination values("Tizi-Ouzou","Algeria","June",5,"DZA4070");
insert into tourist_destination values("Bordj Bou Arreridj","Algeria","August",1,"DZA8580");
insert into tourist_destination values("Msila","Algeria","September",9,"DZA2370");
insert into tourist_destination values("Guelma","Algeria","April",3,"DZA8180");
insert into tourist_destination values("Oum el Bouaghi","Algeria","October",3,"DZA110");
insert into tourist_destination values("Timimoun","Algeria","January",9,"DZA7760");
insert into tourist_destination values("Sidi bel Abbes","Algeria","June",3,"DZA7630");
insert into tourist_destination values("Tlimcen","Algeria","July",8,"DZA6060");
insert into tourist_destination values("Beni Ounif","Algeria","June",4,"DZA8180");
insert into tourist_destination values("Abadla","Algeria","January",8,"DZA3690");
insert into tourist_destination values("Sefra","Algeria","November",7,"DZA9960");
insert into tourist_destination values("Skikda","Algeria","October",3,"DZA4700");
insert into tourist_destination values("Djanet","Algeria","0",0,"(null)0");
insert into tourist_destination values("I-n-Amenas","Algeria","June",5,"DZA6440");
insert into tourist_destination values("In Amguel","Algeria","August",5,"DZA1390");
insert into tourist_destination values("El Bayadh","Algeria","March",6,"DZA6690");
insert into tourist_destination values("El Oued","Algeria","March",2,"DZA4640");
insert into tourist_destination values("Hassi Messaoud","Algeria","February",7,"DZA3550");
insert into tourist_destination values("Chlef","Algeria","June",8,"DZA6110");
insert into tourist_destination values("Mascara","Algeria","March",8,"DZA2990");
insert into tourist_destination values("Mostaganem","Algeria","April",6,"DZA5680");
insert into tourist_destination values("Saida","Algeria","June",2,"DZA3110");
insert into tourist_destination values("Tiarat","Algeria","December",5,"DZA8010");
insert into tourist_destination values("Bejaia","Algeria","February",0,"DZA8780");
insert into tourist_destination values("Blida","Algeria","July",0,"DZA7360");
insert into tourist_destination values("Bouira","Algeria","June",6,"DZA5220");
insert into tourist_destination values("Medea","Algeria","July",8,"DZA4160");
insert into tourist_destination values("Souk Ahras","Algeria","August",8,"DZA9240");
insert into tourist_destination values("Tebessa","Algeria","November",2,"DZA6240");
insert into tourist_destination values("Adrar","Algeria","January",6,"DZA4520");
insert into tourist_destination values("Reggane","Algeria","9",0,"(null)0");
insert into tourist_destination values("Bechar","Algeria","October",1,"DZA9730");
insert into tourist_destination values("Tindouf","Algeria","1",0,"(null)0");
insert into tourist_destination values("Illizi","Algeria","February",4,"DZA6600");
insert into tourist_destination values("Arak","Algeria","April",9,"DZA9810");
insert into tourist_destination values("I-n-Salah","Algeria","6",0,"(null)0");
insert into tourist_destination values("El Golea","Algeria","November",3,"DZA6680");
insert into tourist_destination values("Laghouat","Algeria","March",5,"DZA9260");
insert into tourist_destination values("Touggourt","Algeria","March",4,"DZA3400");
insert into tourist_destination values("Ouargla","Algeria","December",4,"DZA3760");
insert into tourist_destination values("Biskra","Algeria","August",6,"DZA1070");
insert into tourist_destination values("Djelfa","Algeria","November",6,"DZA1790");
insert into tourist_destination values("Setif","Algeria","August",7,"DZA4120");
insert into tourist_destination values("Batna","Algeria","June",2,"DZA6590");
insert into tourist_destination values("Annaba","Algeria","November",6,"DZA2100");
insert into tourist_destination values("Constantine","Algeria","August",7,"DZA2060");
insert into tourist_destination values("Oran","Algeria","November",3,"DZA3720");
insert into tourist_destination values("Tamanrasset","Algeria","February",5,"DZA8190");
insert into tourist_destination values("Ghardaia","Algeria","September",1,"DZA9040");
insert into tourist_destination values("Algiers","Algeria","September",1,"DZA9400");
insert into tourist_destination values("Pago Pago","American Samoa","5",0,"(null)0");
insert into tourist_destination values("Andorra","Andorra","0",0,"(null)0");
insert into tourist_destination values("Mucusso","Angola","December",0,"AGO2240");
insert into tourist_destination values("Lucapa","Angola","December",9,"AGO3960");
insert into tourist_destination values("Capenda-Camulemba","Angola","February",0,"AGO840");
insert into tourist_destination values("Saurimo","Angola","June",2,"AGO6720");
insert into tourist_destination values("Muconda","Angola","March",5,"AGO3850");
insert into tourist_destination values("Cacolo","Angola","March",9,"AGO6400");
insert into tourist_destination values("Caxito","Angola","March",8,"AGO7130");
insert into tourist_destination values("Camabatela","Angola","March",0,"AGO5240");
insert into tourist_destination values("Ndalatando","Angola","March",9,"AGO5810");
insert into tourist_destination values("Quibala","Angola","April",6,"AGO7320");
insert into tourist_destination values("Calulo","Angola","September",4,"AGO40");
insert into tourist_destination values("Waku Kungo","Angola","9",0,"(null)0");
insert into tourist_destination values("Songo","Angola","October",0,"AGO2550");
insert into tourist_destination values("Mbanza-Congo","Angola","June",2,"AGO5790");
insert into tourist_destination values("Nzeto","Angola","June",3,"AGO2050");
insert into tourist_destination values("Soyo","Angola","July",7,"AGO5040");
insert into tourist_destination values("Cabinda","Angola","February",1,"AGO7540");
insert into tourist_destination values("Calucinga","Angola","August",9,"AGO9440");
insert into tourist_destination values("Camacupa","Angola","December",2,"AGO5060");
insert into tourist_destination values("Cubal","Angola","October",1,"AGO8420");
insert into tourist_destination values("Mavinga","Angola","January",8,"AGO1890");
insert into tourist_destination values("Cuito Caunavale","Angola","June",8,"AGO9580");
insert into tourist_destination values("Luiana","Angola","August",6,"AGO8080");
insert into tourist_destination values("Ondjiva","Angola","February",8,"AGO3030");
insert into tourist_destination values("Chitado","Angola","February",3,"AGO6480");
insert into tourist_destination values("Chibemba","Angola","August",4,"AGO5670");
insert into tourist_destination values("Chibia","Angola","August",8,"AGO5290");
insert into tourist_destination values("Quipungo","Angola","October",6,"AGO7880");
insert into tourist_destination values("Luau","Angola","July",9,"AGO9900");
insert into tourist_destination values("Cangamba","Angola","September",3,"AGO3630");
insert into tourist_destination values("Lumbala Nguimbo","Angola","July",3,"AGO8920");
insert into tourist_destination values("Cazombo","Angola","August",5,"AGO1520");
insert into tourist_destination values("Dondo","Angola","June",5,"AGO1880");
insert into tourist_destination values("Sumbe","Angola","November",9,"AGO4360");
insert into tourist_destination values("Uige","Angola","January",4,"AGO9210");
inse
