insert into tourist_destination values("Qal eh-ye","Afghanistan","August",6,"AFG8080");
insert into tourist_destination values("Mariehamn","Aland","August",3,"ALD3720");
insert into tourist_destination values("Kruje","Albania","November",2,"ALB6920");
insert into tourist_destination values("Jijel","Algeria","February",2,"DZA760");
insert into tourist_destination values("Pago Pago","American Samoa","March",9,"ASM8180");
insert into tourist_destination values("Andorra","Andorra","November",0,"AND4870");
insert into tourist_destination values("Mucusso","Angola","May",6,"AGO2780");
insert into tourist_destination values("de Noviembre","Argentina","September",7,"ARG5020");
insert into tourist_destination values("Ashtarak","Armenia","March",0,"ARM9410");
insert into tourist_destination values("Oranjestad","Aruba","August",7,"ABW2200");
insert into tourist_destination values("Central Coast","Australia","June",2,"AUS1130");
insert into tourist_destination values("Bregenz","Austria","July",9,"AUT2640");
insert into tourist_destination values("Gadabay","Azerbaijan","February",6,"AZE1140");
insert into tourist_destination values("Manama","Bahrain","November",9,"BHR4820");
insert into tourist_destination values("Tangail","Bangladesh","October",9,"BGD8990");
insert into tourist_destination values("Bridgetown","Barbados","February",8,"BRB4450");
insert into tourist_destination values("Baranavichy","Belarus","December",0,"BLR5400");
insert into tourist_destination values("Mons","Belgium","November",1,"BEL11130");
insert into tourist_destination values("El Cayo","Belize","September",3,"BLZ10010");
insert into tourist_destination values("Lokossa","Benin","March",6,"BEN4260");
insert into tourist_destination values("Hamilton","Bermuda","October",5,"BMU2350");
insert into tourist_destination values("Paro","Bhutan","April",6,"BTN6620");
insert into tourist_destination values("Punata","Bolivia","November",9,"BOL4760");
insert into tourist_destination values("Zenica","Bosnia and Herzegovina","June",4,"BIH10640");
insert into tourist_destination values("Mochudi","Botswana","July",5,"BWA9890");
insert into tourist_destination values("Grajau","Brazil","April",4,"BRA5450");
insert into tourist_destination values("Bandar Seri Begawan","Brunei","April",0,"BRN2740");
insert into tourist_destination values("Lovec","Bulgaria","January",6,"BGR3710");
insert into tourist_destination values("Fada Ngourma","Burkina Faso","September",4,"BFA6020");
insert into tourist_destination values("Cankuzo","Burundi","December",4,"BDI6040");
insert into tourist_destination values("Kampong Spoe","Cambodia","January",0,"KHM8870");
insert into tourist_destination values("Buea","Cameroon","January",9,"CMR2290");
insert into tourist_destination values("Selkirk","Canada","November",6,"CAN3170");
insert into tourist_destination values("Mindelo","Cape Verde","December",5,"CPV7990");
insert into tourist_destination values("George Town","Cayman Islands","March",8,"CYM7020");
insert into tourist_destination values("Mobaye","Central African Republic","October",7,"CAF11430");
insert into tourist_destination values("Lai","Chad","October",2,"TCD8990");
insert into tourist_destination values("Rio Verde","Chile","September",1,"CHL5330");
insert into tourist_destination values("Yumen","China","March",1,"CHN11240");
insert into tourist_destination values("Yopal","Colombia","June",4,"COL8840");
insert into tourist_destination values("Moroni","Comoros","May",9,"COM3020");
insert into tourist_destination values("Madingou","Congo (Brazzaville)","February",7,"COG10480");
insert into tourist_destination values("Buluko","Congo (Kinshasa)","October",5,"COD9920");
insert into tourist_destination values("Rarotonga","Cook Islands","August",7,"COK11450");
insert into tourist_destination values("Heredia","Costa Rica","June",3,"CRI8810");
insert into tourist_destination values("Sibenik","Croatia","June",6,"HRV9840");
insert into tourist_destination values("Ciego de Avila","Cuba","December",4,"CUB8350");
insert into tourist_destination values("Willemstad","Curacao","April",2,"CUW11420");
insert into tourist_destination values("Larnaka","Cyprus","April",9,"CYP5890");
insert into tourist_destination values("Usti Nad Labem","Czech Republic","January",8,"CZE10400");
insert into tourist_destination values("Vejle","Denmark","May",9,"DNK11270");
insert into tourist_destination values("Dikhil","Djibouti","December",8,"DJI5820");
insert into tourist_destination values("Roseau","Dominica","March",1,"DMA12640");
insert into tourist_destination values("Sabaneta","Dominican Republic","December",9,"DOM8370");
insert into tourist_destination values("Dili","East Timor","September",8,"TLS11960");
insert into tourist_destination values("Puyo","Ecuador","March",3,"ECU8610");
insert into tourist_destination values("Shibin el Kom","Egypt","March",4,"EGY4910");
insert into tourist_destination values("Ahuachapan","El Salvador","November",7,"SLV12290");
insert into tourist_destination values("Evinayong","Equatorial Guinea","April",1,"GNQ6060");
insert into tourist_destination values("Tessenei","Eritrea","February",9,"ERI13210");
insert into tourist_destination values("Haapsalu","Estonia","May",1,"EST8280");
insert into tourist_destination values("Awasa","Ethiopia","May",5,"ETH8040");
insert into tourist_destination values("Fox Bay","Falkland Islands","July",1,"FLK12610");
insert into tourist_destination values("Klaksvik","Faroe Islands","August",9,"FRO6460");
insert into tourist_destination values("Palikir","Federated States of Micronesia","April",3,"FSM12330");
insert into tourist_destination values("Nandi","Fiji","September",3,"FJI4320");
insert into tourist_destination values("Hameenlinna","Finland","January",9,"FIN12030");
insert into tourist_destination values("Annecy","France","May",3,"FRA11960");
insert into tourist_destination values("Papeete","French Polynesia","June",8,"PYF10450");
insert into tourist_destination values("Ebebiyin","Gabon","May",4,"GAB12630");
insert into tourist_destination values("Kutaisi","Georgia","January",8,"GEO8200");
insert into tourist_destination values("Mainz","Germany","October",7,"DEU14530");
insert into tourist_destination values("Sunyani","Ghana","September",3,"GHA9330");
insert into tourist_destination values("Gibraltar","Gibraltar","December",0,"GBR9680");
insert into tourist_destination values("Lamia","Greece","May",5,"GRC11190");
insert into tourist_destination values("Qasigiannguit","Greenland","July",5,"GRD6200");
insert into tourist_destination values("Saint George's","Grenada","March",6,"GRE11560");
insert into tourist_destination values("Agana","Guam","March",2,"GUM9570");
insert into tourist_destination values("Salama","Guatemala","February",7,"GUA8540");
insert into tourist_destination values("Mali","Guinea","May",8,"GUI11160");
insert into tourist_destination values("Cacheu","Guinea Bissau","March",8,"GUB8100");
insert into tourist_destination values("Corriverton","Guyana","April",6,"GUY10850");
insert into tourist_destination values("Jeremie","Haiti","May",2,"HAI8340");
insert into tourist_destination values("Yoro","Honduras","November",5,"HON13300");
insert into tourist_destination values("Hong Kong","Hong Kong S.A.R.","February",0,"HKG14130");
insert into tourist_destination values("Veszprem","Hungary","June",0,"HUN12770");
insert into tourist_destination values("Borgarnes","Iceland","May",6,"ICE10690");
insert into tourist_destination values("Panaji","India","June",8,"IND9690");
insert into tourist_destination values("Binjai","Indonesia","July",8,"INA14830");
insert into tourist_destination values("Yasuj","Iran","October",2,"IRN11890");
insert into tourist_destination values("Dahuk","Iraq","January",6,"IRQ10230");
insert into tourist_destination values("Ros Comain","Ireland","December",9,"IRL11270");
insert into tourist_destination values("Douglas","Isle of Man","September",1,"ISM15560");
insert into tourist_destination values("Ramla","Israel","December",1,"ISR15190");
insert into tourist_destination values("Potenza","Italy","February",4,"ITA12550");
insert into tourist_destination values("Touba","Ivory Coast","April",9,"IVC15820");
insert into tourist_destination values("Lucea","Jamaica","December",6,"JAM15660");
insert into tourist_destination values("Okayama","Japan","October",3,"JPN12810");
insert into tourist_destination values("Al Mafraq","Jordan","March",5,"JOR15450");
insert into tourist_destination values("Turgay","Kazakhstan","March",4,"KZH9650");
insert into tourist_destination values("Nyeri","Kenya","November",4,"KEY10070");
insert into tourist_destination values("Tarawa","Kiribati","July",6,"KIR7440");
insert into tourist_destination values("Prizren","Kosovo","October",6,"KOS8220");
insert into tourist_destination values("Hawalli","Kuwait","July",7,"KUW10610");
insert into tourist_destination values("Tokmak","Kyrgyzstan","May",2,"KYG13140");
insert into tourist_destination values("Ban Houayxay","Laos","October",6,"LAO8710");
insert into tourist_destination values("Rezekne","Latvia","July",7,"LAT8730");
insert into tourist_destination values("B'abda","Lebanon","October",3,"LEB10450");
insert into tourist_destination values("Teyateyaneng","Lesotho","February",5,"LES14980");
insert into tourist_destination values("Barclayville","Liberia","August",1,"LIB15890");
insert into tourist_destination values("Dirj","Libya","August",1,"LBY16310");
insert into tourist_destination values("Vaduz","Liechtenstein","December",5,"LIE9250");
insert into tourist_destination values("Panevezys","Lithuania","December",0,"LIT16870");
insert into tourist_destination values("Diekirch","Luxembourg","November",0,"LXB9330");
insert into tourist_destination values("Macau","Macau S.A.R","November",9,"MAU11110");
insert into tourist_destination values("Tetovo","Macedonia","February",0,"MAC8050");
insert into tourist_destination values("Sambava","Madagascar","May",2,"MAD13990");
insert into tourist_destination values("Mzimba","Malawi","March",5,"MAW11180");
insert into tourist_destination values("Kangar","Malaysia","March",9,"MYL13790");
insert into tourist_destination values("Male","Maldives","March",8,"MDL14580");
insert into tourist_destination values("Goundam","Mali","March",0,"MAL12750");
insert into tourist_destination values("Valletta","Malta","March",9,"MAA13380");
insert into tourist_destination values("Majuro","Marshall Islands","April",6,"MAI14950");
insert into tourist_destination values("Fderik","Mauritania","August",4,"MAN7730");
insert into tourist_destination values("Curepipe","Mauritius","December",9,"MAU10480");
insert into tourist_destination values("Vicente Guerrero","Mexico","September",0,"MEX10360");
insert into tourist_destination values("Dubasari","Moldova","May",2,"MOD13660");
insert into tourist_destination values("Monaco","Monaco","May",3,"MOC9980");
insert into tourist_destination values("Suchboatar","Mongolia","June",7,"MON13030");
insert into tourist_destination values("Podgorica","Montenegro","February",1,"MOG15590");
insert into tourist_destination values("Ksar El Kebir","Morocco","July",9,"MOR17550");
insert into tourist_destination values("Moatize","Mozambique","November",2,"MOZ13230");
insert into tourist_destination values("Loikaw","Myanmar","September",1,"MYN16650");
insert into tourist_destination values("Omaruru","Namibia","January",8,"NMB10180");
insert into tourist_destination values("Sallyan","Nepal","May",8,"NEP17930");
insert into tourist_destination values("Assen","Netherlands","July",6,"NTR16490");
insert into tourist_destination values("Noumea","New Caledonia","February",8,"NCA11500");
insert into tourist_destination values("Greymouth","New Zealand","February",3,"NZL15010");
insert into tourist_destination values("Somoto","Nicaragua","July",4,"NCG14260");
insert into tourist_destination values("Goure","Niger","July",8,"NGR13940");
insert into tourist_destination values("Umuahia","Nigeria","September",6,"NIG16590");
insert into tourist_destination values("Sariwon","North Korea","June",9,"PRK18670");
insert into tourist_destination values("Kyrenia","Northern Cyprus","August",3,"NCY12460");
insert into tourist_destination values("Capitol Hill","Northern Mariana Islands","June",3,"NMI17810");
insert into tourist_destination values("Arendal","Norway","July",5,"NRW10470");
insert into tourist_destination values("Alayat Samail","Oman","May",5,"OMN10890");
insert into tourist_destination values("Parachinar","Pakistan","October",9,"PAK13430");
insert into tourist_destination values("Koror","Palau","January",4,"PAU18340");
insert into tourist_destination values("Ramallah","Palestine","January",4,"PAT9470");
insert into tourist_destination values("El Porvenir","Panama","August",0,"PAN16730");
insert into tourist_destination values("Wabag","Papua New Guinea","May",2,"PNG17250");
insert into tourist_destination values("Mariscal Jose F. Estigarribia","Paraguay","October",9,"PRG9800");
insert into tourist_destination values("Ferrenafe","Peru","December",2,"PER13710");
insert into tourist_destination values("San Carlos","Philippines","April",0,"PHP16300");
insert into tourist_destination values("Olsztyn","Poland","December",8,"POL11140");
insert into tourist_destination values("Aveiro","Portugal","December",5,"PTR10950");
insert into tourist_destination values("Ponce","Puerto Rico","August",2,"PRO11820");
insert into tourist_destination values("Doha","Qatar","April",4,"QTR16020");
insert into tourist_destination values("Targu Jiu","Romania","February",4,"ROM12640");
insert into tourist_destination values("Nazran","Russia","February",3,"RUS13200");
insert into tourist_destination values("Gikongoro","Rwanda","October",0,"RWN12290");
insert into tourist_destination values("Basseterre","Saint Kitts and Nevis","December",9,"SKN12860");
insert into tourist_destination values("Castries","Saint Lucia","December",8,"SLU12950");
insert into tourist_destination values("Apia","Samoa","December",3,"SAM11530");
insert into tourist_destination values("San Marino","San Marino","October",0,"SMA16970");
insert into tourist_destination values("Santo Antonio","Sao Tome and Principe","September",1,"STP15900");
insert into tourist_destination values("An Nabk","Saudi Arabia","March",2,"SAU12880");
insert into tourist_destination values("Fatick","Senegal","July",0,"SEN11500");
insert into tourist_destination values("Subotica","Serbia","April",1,"SER11200");
insert into tourist_destination values("Victoria","Seychelles","October",0,"SYC14700");
insert into tourist_destination values("Makeni","Sierra Leone","September",7,"SLE17280");
insert into tourist_destination values("Singapore","Singapore","July",0,"SGP16830");
insert into tourist_destination values("Banska Bystrica","Slovakia","May",7,"SLO16770");
insert into tourist_destination values("Maribor","Slovenia","September",5,"SLO14270");
insert into tourist_destination values("Gizo","Solomon Islands","September",6,"SOS11750");
insert into tourist_destination values("Xuddur","Somalia","July",6,"SOM20750");
insert into tourist_destination values("Laascaanood","Somaliland","May",2,"SOI16650");
insert into tourist_destination values("Qacha's Nek","South Africa","February",6,"ZSA13830");
insert into tourist_destination values("Grytviken","South Georgia and the Islands","December",0,"SGI11500");
insert into tourist_destination values("Eumseong","South Korea","January",1,"KOR16980");
insert into tourist_destination values("Bentiu","South Sudan","February",7,"SSU14230");
insert into tourist_destination values("Merida","Spain","November",4,"ESP14720");
insert into tourist_destination values("Trincomalee","Sri Lanka","September",0,"SRL15350");
insert into tourist_destination values("Ed Damazin","Sudan","April",0,"SUD20980");
insert into tourist_destination values("Onverwacht","Suriname","October",4,"SUR14900");
insert into tourist_destination values("Piggs Peak","Swaziland","June",0,"SWZ15740");
insert into tourist_destination values("Falun","Sweden","April",8,"SWE14850");
insert into tourist_destination values("Delemont","Switzerland","November",0,"SWI14370");
insert into tourist_destination values("Dar'a","Syria","September",7,"SYR17650");
insert into tourist_destination values("Bade","Taiwan","May",9,"TWN14020");
insert into tourist_destination values("Leninobod","Tajikistan","October",9,"TAJ13880");
insert into tourist_destination values("Wete","Tanzania","July",5,"TAN19600");
insert into tourist_destination values("Mae Hong Son","Thailand","February",8,"THA20560");
insert into tourist_destination values("Freeport","The Bahamas","June",9,"BAH16720");
insert into tourist_destination values("Georgetown","The Gambia","August",8,"GAM19520");
insert into tourist_destination values("Bassar","Togo","November",1,"TOG19300");
insert into tourist_destination values("Neiafu","Tonga","January",9,"TOG18250");
insert into tourist_destination values("San Fernando","Trinidad and Tobago","November",5,"TAT16010");
insert into tourist_destination values("Medemine","Tunisia","July",3,"TUN13760");
insert into tourist_destination values("Kirklareli","Turkey","February",3,"TUR15830");
insert into tourist_destination values("Gyzlarbat","Turkmenistan","November",9,"TKM16480");
insert into tourist_destination values("Grand Turk","Turks and Caicos Islands","August",9,"TCI16000");
insert into tourist_destination values("Funafuti","Tuvalu","November",4,"TVL14160");
insert into tourist_destination values("Kalangala","Uganda","August",1,"UGN17110");
insert into tourist_destination values("Mykolayiv","Ukraine","July",0,"UKR15470");
insert into tourist_destination values("Umm al Qaywayn","United Arab Emirates","August",7,"UAE13760");
insert into tourist_destination values("Greenock","United Kingdom","June",7,"GRB18410");
insert into tourist_destination values("Christiansted","United States Virgin Islands","December",7,"UVG22240");
insert into tourist_destination values("Colonia del Sacramento","Uruguay","April",1,"URG18160");
insert into tourist_destination values("Khujayli","Uzbekistan","September",4,"UZB13150");
insert into tourist_destination values("Luganville","Vanuatu","March",5,"VNT13720");
insert into tourist_destination values("Vatican City","Vatican (Holy Sea)","May",6,"VAT12990");
insert into tourist_destination values("San Carlos","Venezuela","April",9,"VEN20990");
insert into tourist_destination values("Tay Ninh","Vietnam","May",8,"VNM18890");
insert into tourist_destination values("Bir Lehlou","Western Sahara","July",1,"WSA22850");
insert into tourist_destination values("Al Bayda","Yemen","July",2,"YMN17000");
insert into tourist_destination values("Kawambwa","Zambia","October",5,"ZMB18630");
insert into tourist_destination values("Mazowe","Zimbabwe","January",6,"ZMV18160");
insert into tourist_destination values("Beyla","Guinea","December",9,"GUI21960");
insert into tourist_destination values("Gueckedou","Guinea","May",9,"GUI22560");
insert into tourist_destination values("Dinguiraye","Guinea","December",0,"GUI15870");
insert into tourist_destination values("Dabola","Guinea","May",8,"GUI14620");
insert into tourist_destination values("Kerouane","Guinea","April",9,"GUI16070");
insert into tourist_destination values("Siguiri","Guinea","April",5,"GUI23030");
insert into tourist_destination values("Mamou","Guinea","August",5,"GUI23300");
insert into tourist_destination values("Kamsar","Guinea","July",9,"GUI21490");
insert into tourist_destination values("Fria","Guinea","October",8,"GUI21920");
insert into tourist_destination values("Macenta","Guinea","November",2,"GUI23750");
insert into tourist_destination values("Yomou","Guinea","June",0,"GUI14920");
insert into tourist_destination values("Faranah","Guinea","March",6,"GUI19980");
insert into tourist_destination values("Kissidougou","Guinea","July",3,"GUI19540");
insert into tourist_destination values("Labe","Guinea","July",4,"GUI21300");
insert into tourist_destination values("Boke","Guinea","December",7,"GUI21850");
insert into tourist_destination values("Kindia","Guinea","December",8,"GUI23480");
insert into tourist_destination values("Kankan","Guinea","March",2,"GUI17290");
insert into tourist_destination values("Nzerekore","Guinea","June",6,"GUI16760");
insert into tourist_destination values("Conakry","Guinea","February",1,"GUI16000");
insert into tourist_destination values("Cacheu","Guinea Bissau","December",3,"GUB17810");
insert into tourist_destination values("Farim","Guinea Bissau","October",1,"GUB21690");
insert into tourist_destination values("Fulacunda","Guinea Bissau","July",7,"GUB23010");
insert into tourist_destination values("Gabu","Guinea Bissau","December",5,"GUB15610");
insert into tourist_destination values("Catio","Guinea Bissau","March",0,"GUB23810");
insert into tourist_destination values("Bolama","Guinea Bissau","December",1,"GUB21160");
insert into tourist_destination values("Bafata","Guinea Bissau","October",9,"GUB15620");
insert into tourist_destination values("Bissau","Guinea Bissau","January",1,"GUB23000");
insert into tourist_destination values("Corriverton","Guyana","November",8,"GUY20040");
insert into tourist_destination values("Ituni","Guyana","October",6,"GUY17020");
insert into tourist_destination values("Lethem","Guyana","December",9,"GUY16330");
insert into tourist_destination values("Kumaka","Guyana","August",6,"GUY22820");
insert into tourist_destination values("Bartica","Guyana","October",6,"GUY25060");
insert into tourist_destination values("Anna Regina","Guyana","February",0,"GUY15670");
insert into tourist_destination values("Linden","Guyana","December",0,"GUY20550");
insert into tourist_destination values("Mabaruma","Guyana","April",2,"GUY20750");
insert into tourist_destination values("New Amsterdam","Guyana","May",9,"GUY18700");
insert into tourist_destination values("Georgetown","Guyana","March",4,"GUY17270");
insert into tourist_destination values("Jeremie","Haiti","December",4,"HAI16010");
insert into tourist_destination values("Port-De-Paix","Haiti","April",2,"HAI19650");
insert into tourist_destination values("Hinche","Haiti","November",3,"HAI19200");
insert into tourist_destination values("Fort-Liberte","Haiti","July",0,"HAI21520");
insert into tourist_destination values("Jacmel","Haiti","March",9,"HAI21070");
insert into tourist_destination values("Les Cayes","Haiti","April",4,"HAI16730");
insert into tourist_destination values("Gonaives","Haiti","April",2,"HAI18010");
insert into tourist_destination values("Cap-Haitien","Haiti","November",3,"HAI25010");
insert into tourist_destination values("Port-au-Prince","Haiti","July",0,"HAI18870");
insert into tourist_destination values("Yoro","Honduras","August",2,"HON18770");
insert into tourist_destination values("La Esperanza","Honduras","April",1,"HON24690");
insert into tourist_destination values("La Paz","Honduras","August",4,"HON18990");
insert into tourist_destination values("Santa Barbara","Honduras","July",4,"HON19680");
insert into tourist_destination values("Gracias","Honduras","October",7,"HON20040");
insert into tourist_destination values("Nueva Ocotepeque","Honduras","April",1,"HON24210");
insert into tourist_destination values("Yuscaran","Honduras","October",8,"HON23520");
insert into tourist_destination values("Roatan","Honduras","August",3,"HON25900");
insert into tourist_destination values("Nacaome","Honduras","December",9,"HON23910");
insert into tourist_destination values("Santa Rosa de Copan","Honduras","March",7,"HON23890");
insert into tourist_destination values("Trujillo","Honduras","January",8,"HON20090");
insert into tourist_destination values("Brus Laguna","Honduras","November",1,"HON20570");
insert into tourist_destination values("Puerto Lempira","Honduras","July",5,"HON17390");
insert into tourist_destination values("Juticalpa","Honduras","December",9,"HON22520");
insert into tourist_destination values("Comayagua","Honduras","March",0,"HON17150");
insert into tourist_destination values("Choluteca","Honduras","May",9,"HON22440");
insert into tourist_destination values("La Ceiba","Honduras","January",8,"HON18200");
insert into tourist_destination values("San Pedro Sula","Honduras","October",1,"HON18310");
insert into tourist_destination values("Tegucigalpa","Honduras","July",9,"HON21490");
insert into tourist_destination values("Hong Kong","Hong Kong S.A.R.","August",7,"HKG19520");
insert into tourist_destination values("Veszprem","Hungary","August",1,"HUN22670");
insert into tourist_destination values("Zalaegerszeg","Hungary","March",1,"HUN26160");
insert into tourist_destination values("Tatabanya","Hungary","July",9,"HUN23370");
insert into tourist_destination values("Szekszard","Hungary","November",0,"HUN18840");
insert into tourist_destination values("Salgotarjan","Hungary","October",7,"HUN22530");
insert into tourist_destination values("Bekescsaba","Hungary","June",1,"HUN23680");
insert into tourist_destination values("Eger","Hungary","September",3,"HUN27530");
insert into tourist_destination values("Szombathely","Hungary","June",7,"HUN21920");
insert into tourist_destination values("Kecskemet","Hungary","May",5,"HUN21870");
insert into tourist_destination values("Szekesfehervar","Hungary","November",2,"HUN23400");
insert into tourist_destination values("Nyiregyhaza","Hungary","October",2,"HUN19290");
insert into tourist_destination values("Pecs","Hungary","October",6,"HUN22160");
insert into tourist_destination values("Gyor","Hungary","February",8,"HUN24020");
insert into tourist_destination values("Kaposvar","Hungary","August",2,"HUN21100");
insert into tourist_destination values("Vac","Hungary","April",6,"HUN19730");
insert into tourist_destination values("Miskolc","Hungary","June",9,"HUN24120");
insert into tourist_destination values("Szeged","Hungary","January",2,"HUN18520");
insert into tourist_destination values("Debrecen","Hungary","July",3,"HUN26970");
insert into tourist_destination values("Szolnok","Hungary","July",1,"HUN25280");
insert into tourist_destination values("Budapest","Hungary","November",5,"HUN27790");
insert into tourist_destination values("Borgarnes","Iceland","July",3,"ICE21690");
insert into tourist_destination values("Egilsstadir","Iceland","May",6,"ICE26810");
insert into tourist_destination values("Saudarkrokur","Iceland","January",5,"ICE23950");
insert into tourist_destination values("Selfoss","Iceland","August",5,"ICE23630");
insert into tourist_destination values("Hofn","Iceland","September",0,"ICE24970");
insert into tourist_destination values("Isafjordur","Iceland","December",7,"ICE28130");
insert into tourist_destination values("Akureyi","Iceland","July",1,"ICE22010");
insert into tourist_destination values("Keflavik","Iceland","August",8,"ICE21220");
insert into tourist_destination values("Reykjavik","Iceland","December",0,"ICE23400");
insert into tourist_destination values("Panaji","India","June",8,"IND26310");
insert into tourist_destination values("Simla","India","April",0,"IND25720");
insert into tourist_destination values("Gurgaon","India","October",7,"IND20470");
insert into tourist_destination values("Sonipat","India","June",1,"IND25780");
insert into tourist_destination values("Rohtak","India","October",0,"IND24610");
insert into tourist_destination values("Hisar","India","April",8,"IND28270");
insert into tourist_destination values("Bhiwani","India","November",3,"IND25220");
insert into tourist_destination values("Ambala","India","July",6,"IND21500");
insert into tourist_destination values("Sopur","India","May",1,"IND20440");
insert into tourist_destination values("Silvassa","India","October",9,"IND26200");
insert into tourist_destination values("Kalyan","India","November",2,"IND19860");
insert into tourist_destination values("Bhusawal","India","June",5,"IND23430");
insert into tourist_destination values("Jorhat","India","March",4,"IND21760");
insert into tourist_destination values("Hoshiarpur","India","January",5,"IND22530");
insert into tourist_destination values("Ajmer","India","May",4,"IND25210");
insert into tourist_destination values("Hathras","India","September",3,"IND22770");
insert into tourist_destination values("Sitapur","India","October",5,"IND26770");
insert into tourist_destination values("Pilibhit","India","July",5,"IND20110");
insert into tourist_destination values("Budaun","India","June",7,"IND23000");
insert into tourist_destination values("Firozabad","India","May",7,"IND24050");
insert into tourist_destination values("Mathura","India","June",3,"IND23630");
insert into tourist_destination values("Bulandshahr","India","August",4,"IND24560");
insert into tourist_destination values("Hapur","India","December",5,"IND29980");
insert into tourist_destination values("Muzaffarnagar","India","March",1,"IND28090");
insert into tourist_destination values("Gangtok","India","May",1,"IND27690");
insert into tourist_destination values("Diu","India","January",0,"IND27210");
insert into tourist_destination values("Pathankot","India","March",9,"IND22820");
insert into tourist_destination values("Sirsa","India","July",3,"IND20860");
insert into tourist_destination values("Panipat","India","July",1,"IND24410");
insert into tourist_destination values("Karnal","India","March",3,"IND25740");
insert into tourist_destination values("Baramula","India","September",7,"IND26260");
insert into tourist_destination values("Proddatur","India","December",8,"IND29660");
insert into tourist_destination values("Nandyal","India","September",7,"IND29570");
insert into tourist_destination values("Hindupur","India","November",1,"IND30770");
insert into tourist_destination values("Tirupati","India","January",5,"IND26240");
insert into tourist_destination values("Ongole","India","June",7,"IND24800");
insert into tourist_destination values("Vizianagaram","India","December",1,"IND22370");
insert into tourist_destination values("Rajahmundry","India","September",6,"IND27690");
insert into tourist_destination values("Machilipatnam","India","April",4,"IND26260");
insert into tourist_destination values("Khammam","India","May",4,"IND22470");
insert into tourist_destination values("Chirala","India","April",9,"IND22900");
insert into tourist_destination values("Karimnagar","India","September",8,"IND31240");
insert into tourist_destination values("Nizamabad","India","May",0,"IND31170");
insert into tourist_destination values("Kollam","India","May",0,"IND28160");
insert into tourist_destination values("Alappuzha","India","November",5,"IND24870");
insert into tourist_destination values("Puri","India","July",6,"IND23620");
insert into tourist_destination values("Sambalpur","India","April",9,"IND27200");
insert into tourist_destination values("Raurkela","India","January",1,"IND25840");
insert into tourist_destination values("Kavaratti","India","July",9,"IND23060");
insert into tourist_destination values("Mandya","India","August",3,"IND24670");
insert into tourist_destination values("Kolar","India","April",8,"IND25040");
insert into tourist_destination values("Shimoga","India","June",3,"IND30480");
insert into tourist_destination values("Raichur","India","March",9,"IND25760");
insert into tourist_destination values("Hospet","India","December",3,"IND26950");
insert into tourist_destination values("Bidar","India","September",0,"IND31660");
insert into tourist_destination values("Sangli","India","August",6,"IND24100");
insert into tourist_destination values("Parbhani","India","November",7,"IND23850");
insert into tourist_destination values("Malegaon","India","October",1,"IND30120");
insert into tourist_destination values("Port Blair","India","March",3,"IND23070");
insert into tourist_destination values("Tezpur","India","September",4,"IND23380");
insert into tourist_destination values("Silchar","India","May",2,"IND28930");
insert into tourist_destination values("Kohima","India","August",9,"IND25640");
insert into tourist_destination values("Shillong","India","May",9,"IND25190");
insert into tourist_destination values("Abohar","India","August",6,"IND26700");
insert into tourist_destination values("Patiala","India","December",3,"IND26360");
insert into tourist_destination values("Bhilwara","India","January",6,"IND32800");
insert into tourist_destination values("Pali","India","April",6,"IND23160");
insert into tourist_destination values("Tonk","India","December",2,"IND25030");
insert into tourist_destination values("Sikar","India","June",2,"IND31850");
insert into tourist_destination values("Bikaner","India","August",2,"IND24970");
insert into tourist_destination values("Bharatpur","India","December",8,"IND25450");
insert into tourist_destination values("Alwar","India","December",7,"IND28220");
insert into tourist_destination values("Fatehpur","India","May",3,"IND32980");
insert into tourist_destination values("Faizabad","India","November",5,"IND32800");
insert into tourist_destination values("Bahraich","India","October",6,"IND27710");
insert into tourist_destination values("Mirzapur","India","October",3,"IND30850");
insert into tourist_destination values("Jhansi","India","March",0,"IND27580");
insert into tourist_destination values("Shahjahanpur","India","February",8,"IND26760");
insert into tourist_destination values("Rampur","India","March",9,"IND29360");
insert into tourist_destination values("Bareilly","India","November",0,"IND29450");
insert into tourist_destination values("Etawah","India","May",9,"IND26690");
insert into tourist_destination values("Dehra Dun","India","June",2,"IND24050");
insert into tourist_destination values("Haora","India","May",6,"IND29840");
insert into tourist_destination values("Alipur Duar","India","February",0,"IND31150");
