insert into tourist_destination values("Qal eh-ye","Afghanistan","August",6,"AFG7770");
insert into tourist_destination values("Chaghcharan","Afghanistan","August",3,"AFG3350");
insert into tourist_destination values("Lashkar Gah","Afghanistan","November",2,"AFG6490");
insert into tourist_destination values("Zaranj","Afghanistan","February",2,"AFG270");
insert into tourist_destination values("Tarin Kowt","Afghanistan","March",9,"AFG7630");
insert into tourist_destination values("Zareh Sharan","Afghanistan","November",0,"AFG4260");
insert into tourist_destination values("Asadabad","Afghanistan","May",6,"AFG2110");
insert into tourist_destination values("Taloqan","Afghanistan","September",7,"AFG4290");
insert into tourist_destination values("Mahmud-E Eraqi","Afghanistan","March",0,"AFG8620");
insert into tourist_destination values("Mehtar Lam","Afghanistan","August",7,"AFG1350");
insert into tourist_destination values("Baraki Barak","Afghanistan","June",2,"AFG220");
insert into tourist_destination values("Aybak","Afghanistan","July",9,"AFG1670");
insert into tourist_destination values("Mayda Shahr","Afghanistan","February",6,"AFG110");
insert into tourist_destination values("Karokh","Afghanistan","November",9,"AFG3730");
insert into tourist_destination values("Sheberghan","Afghanistan","October",9,"AFG7840");
insert into tourist_destination values("Pol-e Khomri","Afghanistan","February",8,"AFG3240");
insert into tourist_destination values("Balkh","Afghanistan","December",0,"AFG4130");
insert into tourist_destination values("Meymaneh","Afghanistan","November",1,"AFG9800");
insert into tourist_destination values("Andkhvoy","Afghanistan","September",3,"AFG8620");
insert into tourist_destination values("Qalat","Afghanistan","March",6,"AFG2810");
insert into tourist_destination values("Ghazni","Afghanistan","October",5,"AFG840");
insert into tourist_destination values("Feyzabad","Afghanistan","April",6,"AFG5050");
insert into tourist_destination values("Kondoz","Afghanistan","November",9,"AFG3130");
insert into tourist_destination values("Jalalabad","Afghanistan","June",4,"AFG8950");
insert into tourist_destination values("Charikar","Afghanistan","July",5,"AFG8140");
insert into tourist_destination values("Gardiz","Afghanistan","April",4,"AFG3640");
insert into tourist_destination values("Bamian","Afghanistan","April",0,"AFG870");
insert into tourist_destination values("Baghlan","Afghanistan","January",6,"AFG1780");
insert into tourist_destination values("Farah","Afghanistan","September",4,"AFG4030");
insert into tourist_destination values("Herat","Afghanistan","December",4,"AFG3990");
insert into tourist_destination values("Mazar-e Sharif","Afghanistan","January",0,"AFG6760");
insert into tourist_destination values("Kandahar","Afghanistan","January",9,"AFG120");
insert into tourist_destination values("Kabul","Afghanistan","November",6,"AFG940");
insert into tourist_destination values("Mariehamn","Aland","December",5,"ALD5700");
insert into tourist_destination values("Kruje","Albania","March",8,"ALB4670");
insert into tourist_destination values("Fier","Albania","October",7,"ALB9020");
insert into tourist_destination values("Lushnje","Albania","October",2,"ALB6520");
insert into tourist_destination values("Puke","Albania","September",1,"ALB2800");
insert into tourist_destination values("Bajram Curri","Albania","March",1,"ALB8650");
insert into tourist_destination values("Kukes","Albania","June",4,"ALB6190");
insert into tourist_destination values("Sarande","Albania","May",9,"ALB310");
insert into tourist_destination values("Erseke","Albania","February",7,"ALB7710");
insert into tourist_destination values("Pogradec","Albania","October",5,"ALB7090");
insert into tourist_destination values("Korce","Albania","August",7,"ALB8560");
insert into tourist_destination values("Berat","Albania","June",3,"ALB5860");
insert into tourist_destination values("Corovode","Albania","June",6,"ALB6830");
insert into tourist_destination values("Gramsh","Albania","December",4,"ALB5280");
insert into tourist_destination values("Librazhd","Albania","April",2,"ALB8290");
insert into tourist_destination values("Tepelene","Albania","April",9,"ALB2700");
insert into tourist_destination values("Permet","Albania","January",8,"ALB7150");
insert into tourist_destination values("Gjirokaster","Albania","May",9,"ALB7960");
insert into tourist_destination values("Peshkopi","Albania","December",8,"ALB2450");
insert into tourist_destination values("Burrel","Albania","March",1,"ALB9210");
insert into tourist_destination values("Lezhe","Albania","December",9,"ALB4880");
insert into tourist_destination values("Rreshen","Albania","September",8,"ALB8410");
insert into tourist_destination values("Vlore","Albania","March",3,"ALB5000");
insert into tourist_destination values("Elbasan","Albania","March",4,"ALB1240");
insert into tourist_destination values("Durres","Albania","November",7,"ALB8560");
insert into tourist_destination values("Shkoder","Albania","April",1,"ALB2270");
insert into tourist_destination values("Tirana","Albania","February",9,"ALB9360");
insert into tourist_destination values("Jijel","Algeria","May",1,"DZA4370");
insert into tourist_destination values("Tizi-Ouzou","Algeria","May",5,"DZA4070");
insert into tourist_destination values("Bordj Bou Arreridj","Algeria","July",1,"DZA8580");
insert into tourist_destination values("Msila","Algeria","August",9,"DZA2370");
insert into tourist_destination values("Guelma","Algeria","April",3,"DZA8180");
insert into tourist_destination values("Oum el Bouaghi","Algeria","September",3,"DZA110");
insert into tourist_destination values("Timimoun","Algeria","January",9,"DZA7760");
insert into tourist_destination values("Sidi bel Abbes","Algeria","May",3,"DZA7630");
insert into tourist_destination values("Tlimcen","Algeria","June",8,"DZA6060");
insert into tourist_destination values("Beni Ounif","Algeria","May",4,"DZA8180");
insert into tourist_destination values("Abadla","Algeria","January",8,"DZA3690");
insert into tourist_destination values("Sefra","Algeria","October",7,"DZA9960");
insert into tourist_destination values("Skikda","Algeria","September",3,"DZA4700");
insert into tourist_destination values("Djanet","Algeria","December",0,"DZA4990");
insert into tourist_destination values("I-n-Amenas","Algeria","May",5,"DZA6440");
insert into tourist_destination values("In Amguel","Algeria","July",5,"DZA1390");
insert into tourist_destination values("El Bayadh","Algeria","March",6,"DZA6690");
insert into tourist_destination values("El Oued","Algeria","March",2,"DZA4640");
insert into tourist_destination values("Hassi Messaoud","Algeria","February",7,"DZA3550");
insert into tourist_destination values("Chlef","Algeria","May",8,"DZA6110");
insert into tourist_destination values("Mascara","Algeria","March",8,"DZA2990");
insert into tourist_destination values("Mostaganem","Algeria","April",6,"DZA5680");
insert into tourist_destination values("Saida","Algeria","May",2,"DZA3110");
insert into tourist_destination values("Tiarat","Algeria","November",5,"DZA8010");
insert into tourist_destination values("Bejaia","Algeria","February",0,"DZA8780");
insert into tourist_destination values("Blida","Algeria","June",0,"DZA7360");
insert into tourist_destination values("Bouira","Algeria","May",6,"DZA5220");
insert into tourist_destination values("Medea","Algeria","June",8,"DZA4160");
insert into tourist_destination values("Souk Ahras","Algeria","July",8,"DZA9240");
insert into tourist_destination values("Tebessa","Algeria","October",2,"DZA6240");
insert into tourist_destination values("Adrar","Algeria","January",6,"DZA4520");
insert into tourist_destination values("Reggane","Algeria","December",9,"DZA5500");
insert into tourist_destination values("Bechar","Algeria","September",1,"DZA9730");
insert into tourist_destination values("Tindouf","Algeria","December",1,"DZA9300");
insert into tourist_destination values("Illizi","Algeria","February",4,"DZA6600");
insert into tourist_destination values("Arak","Algeria","April",9,"DZA9810");
insert into tourist_destination values("I-n-Salah","Algeria","December",6,"DZA9590");
insert into tourist_destination values("El Golea","Algeria","October",3,"DZA6680");
insert into tourist_destination values("Laghouat","Algeria","March",5,"DZA9260");
insert into tourist_destination values("Touggourt","Algeria","March",4,"DZA3400");
insert into tourist_destination values("Ouargla","Algeria","November",4,"DZA3760");
insert into tourist_destination values("Biskra","Algeria","July",6,"DZA1070");
insert into tourist_destination values("Djelfa","Algeria","October",6,"DZA1790");
insert into tourist_destination values("Setif","Algeria","July",7,"DZA4120");
insert into tourist_destination values("Batna","Algeria","May",2,"DZA6590");
insert into tourist_destination values("Annaba","Algeria","October",6,"DZA2100");
insert into tourist_destination values("Constantine","Algeria","July",7,"DZA2060");
insert into tourist_destination values("Oran","Algeria","October",3,"DZA3720");
insert into tourist_destination values("Tamanrasset","Algeria","February",5,"DZA8190");
insert into tourist_destination values("Ghardaia","Algeria","August",1,"DZA9040");
insert into tourist_destination values("Algiers","Algeria","August",1,"DZA9400");
insert into tourist_destination values("Pago Pago","American Samoa","December",5,"ASM2280");
insert into tourist_destination values("Andorra","Andorra","December",0,"AND9840");
insert into tourist_destination values("Mucusso","Angola","November",0,"AGO2240");
insert into tourist_destination values("Lucapa","Angola","November",9,"AGO3960");
insert into tourist_destination values("Capenda-Camulemba","Angola","February",0,"AGO840");
insert into tourist_destination values("Saurimo","Angola","May",2,"AGO6720");
insert into tourist_destination values("Muconda","Angola","March",5,"AGO3850");
insert into tourist_destination values("Cacolo","Angola","March",9,"AGO6400");
insert into tourist_destination values("Caxito","Angola","March",8,"AGO7130");
insert into tourist_destination values("Camabatela","Angola","March",0,"AGO5240");
insert into tourist_destination values("Ndalatando","Angola","March",9,"AGO5810");
insert into tourist_destination values("Quibala","Angola","April",6,"AGO7320");
insert into tourist_destination values("Calulo","Angola","August",4,"AGO40");
insert into tourist_destination values("Waku Kungo","Angola","December",9,"AGO2730");
insert into tourist_destination values("Songo","Angola","September",0,"AGO2550");
insert into tourist_destination values("Mbanza-Congo","Angola","May",2,"AGO5790");
insert into tourist_destination values("Nzeto","Angola","May",3,"AGO2050");
insert into tourist_destination values("Soyo","Angola","June",7,"AGO5040");
insert into tourist_destination values("Cabinda","Angola","February",1,"AGO7540");
insert into tourist_destination values("Calucinga","Angola","July",9,"AGO9440");
insert into tourist_destination values("Camacupa","Angola","November",2,"AGO5060");
insert into tourist_destination values("Cubal","Angola","September",1,"AGO8420");
insert into tourist_destination values("Mavinga","Angola","January",8,"AGO1890");
insert into tourist_destination values("Cuito Caunavale","Angola","May",8,"AGO9580");
insert into tourist_destination values("Luiana","Angola","July",6,"AGO8080");
insert into tourist_destination values("Ondjiva","Angola","February",8,"AGO3030");
insert into tourist_destination values("Chitado","Angola","February",3,"AGO6480");
insert into tourist_destination values("Chibemba","Angola","July",4,"AGO5670");
insert into tourist_destination values("Chibia","Angola","July",8,"AGO5290");
insert into tourist_destination values("Quipungo","Angola","September",6,"AGO7880");
insert into tourist_destination values("Luau","Angola","June",9,"AGO9900");
insert into tourist_destination values("Cangamba","Angola","August",3,"AGO3630");
insert into tourist_destination values("Lumbala Nguimbo","Angola","June",3,"AGO8920");
insert into tourist_destination values("Cazombo","Angola","July",5,"AGO1520");
insert into tourist_destination values("Dondo","Angola","May",5,"AGO1880");
insert into tourist_destination values("Sumbe","Angola","October",9,"AGO4360");
insert into tourist_destination values("Uige","Angol